services:
  automail-app:
    build:
      context: .
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - SITE_URL=${SITE_URL}    
    container_name: automail-app
    ports:
      - "80:80"
    # links:                      # ← optional: safe to remove
    #   - automail-db
    depends_on:                   # ← preferred over links
      - automail-db
    volumes:
      ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
      #- ./data:/www/html
      ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
      - ./data:/data
      ### If you want to just keep the original source and add additional modules uncomment this line
      #- ./modules:/www/html/Modules
      - ./logs/:/www/logs
    environment:
      - CONTAINER_NAME=${CONTAINER_NAME:-automail-app}
      - APPLICATION_NAME=${APPLICATION_NAME:-Automail}
      - DEBUG_MODE=${DEBUG_MODE:-TRUE}
      - DB_HOST=${DB_HOST:-automail-db}
      - DB_NAME=${DB_NAME:-automail}
      - DB_USER=${DB_USER:-automail}
      - DB_PASS=${DB_PASS:-automail}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASS=${ADMIN_PASS}                             # ← rotate after bootstrap
      - APP_TRUSTED_PROXIES=${APP_TRUSTED_PROXIES:-127.0.0.1}                   # ← removed quotes
      - ENABLE_SSL_PROXY=${ENABLE_SSL_PROXY:-TRUE}                            # ← was FALSE
      - DISPLAY_ERRORS=${DISPLAY_ERRORS:-false}
      - TIMEZONE=${TIMEZONE:-Europe/Amsterdam}
      - ENABLE_AUTO_UPDATE=${ENABLE_AUTO_UPDATE:-false}
      - SETUP_TYPE=${SETUP_TYPE:-MANUAL}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-2048M}            # Increase PHP memory limit to 2GB
      - PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-600}  # Increase max execution time to 10 min
      - PHP_MAX_INPUT_TIME=${PHP_MAX_INPUT_TIME:-600}          # Increase max input time to 10 min
      - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE:-500M}           # Increase post max size to 500MB
      - PHP_UPLOAD_MAX_SIZE=${PHP_UPLOAD_MAX_SIZE:-500M}       # Increase upload max size to 500MB
    restart: always

  automail-db:
    image: tiredofit/mariadb
    container_name: automail-db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=${DB_ROOT_PASS:-password}
      - DB_NAME=${DB_NAME:-automail}
      - DB_USER=${DB_USER:-automail}
      - DB_PASS=${DB_PASS:-automail}
      - CONTAINER_NAME=${DB_CONTAINER_NAME:-automail-db}
    restart: always

  automail-db-backup:
    container_name: automail-db-backup
    image: tiredofit/db-backup
    # links:                     # ← optional: safe to remove
    #   - automail-db
    depends_on:                  # ← preferred over links
      - automail-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - CONTAINER_NAME=${BACKUP_CONTAINER_NAME:-automail-db-backup}
      - DB_HOST=${DB_HOST:-automail-db}
      - DB_TYPE=${DB_TYPE:-mariadb}
      - DB_NAME=${DB_NAME:-automail}
      - DB_USER=${DB_USER:-automail}
      - DB_PASS=${DB_PASS:-automail}
      - DB01_BACKUP_INTERVAL=${BACKUP_INTERVAL:-1440}
      - DB01_BACKUP_BEGIN=${BACKUP_BEGIN:-0000}
      - DB_CLEANUP_TIME=${DB_CLEANUP_TIME:-8640}
      - COMPRESSION=${COMPRESSION:-BZ}
      - MD5=${MD5:-TRUE}
    restart: always
